### ISSUE TITLE
`lwc/consistent-component-name` does not work correctly with TypeScript

### ISSUE THREAD

**Issue by TwoPlusTwoOne** [salesforce/eslint-plugin-lwc#109]
When defining the `lwc/consistent-component-name` rule in the eslint config, the linter tries to correct the exported class name to one including the `.ts` extension.

File name: `console.ts`

Class name: `Console`

Error message from linter: `Lightning component class should be named "Console.ts"`

**Comment by pmdartus** [comment]
Fixed by #110.
