### ISSUE TITLE
Show lint warning for createContentDocumentAndVersion

### ISSUE THREAD

**Issue by sfdctaka** [salesforce/eslint-plugin-lwc#126]
LDS function createContentDocumentAndVersion is draft aware for offline. But offline feature is only available for mobile apps only. Eslint should show a warning if createContentDocumentAndVersion is used, regardless of the LWC using it is for desktop and/or for mobile, that the function is draft aware only when used in mobile.

cc: @khawkins

**Comment by ekashida** [comment]
For posterity, this was discussed in a [different thread](https://salesforce-internal.slack.com/archives/C5W3E40TC/p1689282153763219) and the conclusion was that introducing a non-fixable warning for the customer audience is unprecedented, and would require further discussion.

Closing for now, but feel free to reopen if you'd like to pick up the discussion where we left off.
