### ISSUE TITLE
Add validation for usage of unwrap() on DOM elements

### ISSUE THREAD

**Issue by ravijayaramappa** [salesforce/eslint-plugin-lwc#14]
Before LWC GA, dom elements were being wrapped in a proxy. unwrap() was a way to peel away the proxy and access the native element. Post GA, lwc has stopped wrapping elements in a proxy. So the unwrap() call is basically a no-op and waste of CPU cycles. 

Add an eslint rule to flag usages of unwrap() on dom elements.

**Comment by pmdartus** [comment]
Since it's not something that is exposed to the platform. I feel reluctant about adding such linting rule here. I will close this issue, for now, @ravijayaramappa feel free to reopen the issue if you think it's something we really need to pursue.
