### ISSUE TITLE
Restrict usage of async operations (no-async-operation)

### ISSUE THREAD

**Issue by joeythomaschaske** [salesforce/eslint-plugin-lwc#18]
The eslint error for timeouts are a bit misleading when the lwc documentation uses them for debouncing

https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.apex

**Comment by trevor-bliss** [comment]
That rule is categorized as a best practice rule and is really a recommendation to try to avoid things like `setTimeout` unless they are truly necessary. Sometimes that is the case and you can always disable the rule for those usages.
