### ISSUE TITLE
Add details why having a public property default value set to true is invalid

### ISSUE THREAD

**Issue by pmdartus** [salesforce/eslint-plugin-lwc#44]
The following code ... 

```js
export default class MyComponent extends LightningElement {
	@api myBool = true;
} 
```

... triggers this linting error.

```
Error:(13, 16) LWC1503: Invalid public property initialization for "myBool". Boolean public properties should not be initialized to "true", consider initializing the property to "false".
```

This linting error is confusing to developers and the `@lwc/valid-api` linting rule documentation doesn't give more details about this specific error and how to fix it.

**Comment by apapko** [comment]
Public doc for boolean props: https://developer.salesforce.com/docs/component-library/documentation/en/lwc/js_props_boolean

**Comment by pmdartus** [comment]
It would be great to add more details in the eslint rule documentation on top of the official documentation. Since this is the first place I would look into when seeing this error.
